### PR TITLE
Remove linting errors from ./lib/index.spec.js

### PR DESCRIPTION
**Pull request by baer**
Correct Linting Errors caused by me...

### CODE REVIEW

**Comment by baer** [comment]
I see you already took care of this.

**Comment by divmain** [comment]
I beat you to the punch with 80c1afd9768510d4e826127ee240ae5d58f1c710 :)

**Comment by baer** [comment]
Sorry, that was careless of me. My PRs are supposed to take work OFF of you plate not add to it. :smile:

**Comment by divmain** [comment]
Meh, I didn't mind.  Sometimes easy-to-solve problems are cathartic :)

**Pull request closed without merging**
